### ISSUE TITLE
关于数据的疑问

### ISSUE THREAD

**Issue by rm-rf-me** [hpzhang94/hegel_sum#1]
您好，最近看到了您的工作感觉很有新意，想尝试运行您的代码，但我在训练数据上遇到了问题。

想要请教您代码中使用的npy文件是怎样处理得到的，在您文中提及的Cohan et al.,2018那篇文章中下载到的两个数据都是txt格式的。从您本项目README文件的末尾来看，您似乎打算分享你们的数据？但是链接没有挂载成功？

不知您能否分享一下数据集的链接，期待您的回复！

**Comment by nlpxxx** [comment]
同问，请问txt和npy数据集格式是一样的吗？能否提供一下数据集呢。
非常感谢！

**Comment by MoLICHENXI** [comment]
@rm-rf-me @nlpxxx 我是刚刚看到这份2022年的工作 请问txt格式的文件是否直接转换成npy格式的文件就可以直接运行 还是作者经过了清洗并转换成npy文件了呢？
期待您们的回复！
也期待 @hpzhang94  您的回复！谢谢您！

**Comment by Junzizaiji** [comment]
你好，这个问题你有解决吗

**Comment by Junzizaiji** [comment]
> @rm-rf-me @nlpxxx 我是刚刚看到这份2022年的工作 请问txt格式的文件是否直接转换成npy格式的文件就可以直接运行 还是作者经过了清洗并转换成npy文件了呢？ 期待您们的回复！ 也期待 @hpzhang94 您的回复！谢谢您！

你好，这个问题你有解决吗

**Comment by Junzizaiji** [comment]
> 同问，请问txt和npy数据集格式是一样的吗？能否提供一下数据集呢。 非常感谢！

你好，这个问题你有解决吗

**Comment by hpzhang94** [comment]
Please refer to [https://github.com/Wendy-Xiao/Extsumm_local_global_context](url) for the processed data of Pubmed and arXiv datasets.
